# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14nMCkpb8fWAaR5tADPW4acM3ImnCXav_

**Calculadora**
"""

oper=input("ingrese la operación a realizar: ")
if oper=="sumar":
  def sumar(a,b):
    sum= a+b
    return sum
  a=int(input("ingrese primer número: "))
  b=int(input("ingrese segundo número: " ))
  x=suma(a,b)
  print("el resultado es: ",x)
elif oper== "restar":
  def restar(a,b):
    res= a-b
    return res
  a=int(input("ingrese primer número: "))
  b=int(input("ingrese segundo número: "))
  r=restar(a,b)
  print(" el resultado es: ",r)

elif oper== "multiplicar":
  def multiplicar(a,b):
    mul= a*b
    return mul
  a=int(input("ingrese primer número: "))
  b=int(input("ingrese segundo número: "))
  r=multiplicar(a,b)
  print(" el resultado es: ",r)

elif oper== "dividir":
  def dividir(a,b):
    div= a/b
    return div
  a=int(input("ingrese primer número: "))
  b=int(input("ingrese segundo número: "))
  r=dividir(a,b)
  print(" el resultado es: ",r)

else: 
  print("operación no válida")

