# -*- coding: utf-8 -*-
"""Obtener información PC Y Red.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RtAER6m2I98izDAZrpfRViojlLN7cOY8
"""

import platform as pl
import psutil as ps
from datetime import datetime
import socket

def get_size(bytes,suffix="B"):
  factor=1024
  for unit in ["","K","M","G","T","P"]:
    if bytes < factor:
      return f"{bytes:.2f}{unit}{suffix}"
    bytes/=factor

print("="*20,"información del PC","="*20)
uname =pl.uname()
print(f"sistema:{uname.system}")
print(f"procesador: {uname.processor}")
cpufr=ps.cpu_freq()
print("Nucleos:",ps.cpu_count(logical=True))

print("="*16,"información de la memoria","="*16)
svmem=ps.virtual_memory()
print(f"total:{get_size(svmem.total)}")
print(f"disponible: {get_size(svmem.available)}")

print("="*16,"información de la Red","="*16)
def obtener_info_equipo():
		 nombre_equipo = socket.gethostname()
		 direccion_equipo = socket.gethostbyname(nombre_equipo)
		 print ("el nombre del equipo es: %s" % nombre_equipo)
		 print ("La IP es: %s" % direccion_equipo)

if __name__ == '__main__':
		 obtener_info_equipo()